debug: true
fancy_fonts: true
grayscale_mode: false
max_fps: 60
puzzle_1_difficulty: 10
puzzle_1_difficulty_mult: 870
puzzle_1_difficulty_speed: 7
puzzle_2_difficulty_number: 29
puzzle_2_difficulty_speed: 6
screen_height: 1080
screen_width: 1920
subtitles: true
window_mode: fullscreen
