debug: true
fancy_fonts: true
grayscale_mode: false
keybind_down: s
keybind_interact: left shift
keybind_left: a
keybind_right: d
keybind_up: w
max_fps: 60
puzzle_1_difficulty: 10
puzzle_1_difficulty_mult: 870
puzzle_1_difficulty_speed: 7
puzzle_2_difficulty_number: 20
puzzle_2_difficulty_speed: 10
screen_height: 1080
screen_width: 1920
subtitles: true
window_mode: windowed
